FROM rust:1.98-bookworm

WORKDIR /app

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./

RUN mkdir src \
  && echo 'fn main() {}' > src/main.rs \
  && cargo build \
  && rm -rf src

COPY . .

EXPOSE 8080

CMD [ "cargo", "watch", "-x", "run" ]
